length_in_x: 12.0
length_in_y: 12.0
position_x: 0.0
position_y: 0.0
track_point_x: 0.0
track_point_y: 0.0
resolution: 0.2
travers_threshold: 0.4
min_variance: 0.0001
max_variance: 10000.0
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.00002 
